# Generated by Django 2.2.3 on 2019-07-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardTraduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageUrl', models.URLField(max_length=250)),
                ('language', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=1000)),
                ('colorIdentity', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deckName', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SubTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtype', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SuperTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supertype', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CardU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardName', models.CharField(max_length=1000, null=True)),
                ('mana', models.CharField(max_length=1000, null=True)),
                ('cmc', models.IntegerField(default=0)),
                ('typeCard', models.CharField(max_length=1000, null=True)),
                ('rarity', models.CharField(max_length=100, null=True)),
                ('power', models.CharField(max_length=100, null=True)),
                ('multiverseid', models.IntegerField(default=0)),
                ('imageUrl', models.URLField(max_length=250, null=True)),
                ('colors', models.ManyToManyField(null=True, related_name='cardUs', to='app.Color')),
                ('types', models.ManyToManyField(to='app.Types')),
            ],
        ),
    ]
