# Generated by Django 2.2.3 on 2019-08-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='user',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
