# Generated by Django 2.2.3 on 2019-08-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190820_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='user',
        ),
        migrations.AddField(
            model_name='deck',
            name='user',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
