# Generated by Django 2.2.3 on 2019-08-20 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190820_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deck',
            old_name='user',
            new_name='userId',
        ),
    ]
