# Generated by Django 2.2.3 on 2019-08-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190820_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardu',
            name='text',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
