# Generated by Django 2.2.3 on 2019-08-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_cardu_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardu',
            name='number',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
