# Generated by Django 2.2.3 on 2019-08-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190822_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardtraduction',
            name='cardId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardtraduction',
            name='text',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
