# Generated by Django 2.2.3 on 2019-08-21 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190822_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardu',
            name='traduction',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
